#! /bin/bash
# This software is a part of the A.O.D apprepo project
# Copyright 2020 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
set -ex

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${APPDIR}/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH

PATH=$PATH:${APPDIR}/bin
export PATH=$PATH

cd ${OWD}

${APPDIR}/bin/epson-printer-utility $@
